package com.poryvai.post.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

/**
 * Represents a Client in the postal system.
 * Clients can be senders or recipients of parcels.
 * This entity maps to the 'client' table in the database.
 */
@Entity
@Table(name = "client")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
public class Client {

    /**
     * Unique identifier for the client in the database.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * The first name of the client.
     */
    @Column(name = "first_name", nullable = false, length = 64)
    private String firstName;

    /**
     * The last name of the client.
     */
    @Column(name = "last_name", nullable = false, length = 64)
    private String lastName;

    /**
     * The email address of the client. Must be unique across all clients.
     */
    @Column(name = "email", nullable = false, length = 255)
    private String email;

    /**
     * The phone number of the client.
     */
    @Column(name = "phone", nullable = false, length = 20)
    private String phone;
}
