package com.poryvai.post.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

/**
 * Represents an Employee entity in the postal service system.
 * This class maps to a database table and holds essential details about a specific employee,
 * such as their name and current position.
 * It serves as a core domain object for managing personnel within various post offices
 * and tracking their actions related to parcels.
 */
@Entity
@Table(name = "employee")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
public class Employee {

    /**
     * Unique identifier for the Employee in the database.
     * This ID is auto-generated by the database upon entity persistence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * The first name of the employee.
     */
    @Column(name = "first_name", nullable = false, length = 64)
    private String firstName;

    /**
     * The last name of the employee.
     */
    @Column(name = "last_name", nullable = false, length = 64)
    private String lastName;

    /**
     * The position or role of the employee within the postal service (e.g., "Manager", "Clerk", "Driver").
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "position", nullable = false, length = 80)
    private EmployeePosition position;
}
