package com.poryvai.post.model;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldNameConstants;

/**
 * Represents a parcel entity in the system.
 * This class maps to a database table and holds all details about a specific parcel,
 * including its tracking information, sender, recipient, weight, price, and status.
 */
@Entity
@Table(name = "parcel")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
public class Parcel {

    /**
     * Unique identifier for the parcel in the database.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Unique tracking number for the parcel, generated as a UUID.
     * Used for external tracking and lookup.
     */
    @Column(name = "tracking_number", unique = true, nullable = false)
    private String trackingNumber;

    /**
     * The {@link Client} entity representing the sender of the parcel.
     * This field establishes a many-to-one relationship with the Client entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_sender_id", nullable = false)
    private Client senderClient;


    /**
     * The {@link Client} entity representing the recipient of the parcel.
     * This field establishes a many-to-one relationship with the Client entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_recipient_id", nullable = false)
    private Client recipientClient;

    /**
     * The weight of the parcel in kilograms.
     */
    @Column(name = "weight", nullable = false)
    private double weight;

    /**
     * The calculated price for delivering the parcel.
     */
    @Column(name = "price", nullable = false)
    private double price;

    /**
     * The current status of the parcel in its delivery lifecycle.
     * Stored as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private ParcelStatus status;

    /**
     * The type of delivery chosen for the parcel.
     * Stored as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "delivery_type", nullable = false, length = 20)
    private DeliveryType deliveryType;

    /**
     * The type of description chosen for the parcel.
     * Stored as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "description", nullable = false, length = 20)
    private ParcelDescription parcelDescription;

    /**
     * The {@link PostOffice} entity representing the origin post office
     * from which the parcel was sent.
     * This field establishes a many-to-one relationship with the PostOffice entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "origin_post_office_id", nullable = false)
    private PostOffice originPostOffice;

    /**
     * The {@link PostOffice} entity representing the destination post office
     * where the parcel is intended to be delivered.
     * This field establishes a many-to-one relationship with the PostOffice entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "destination_post_office_id", nullable = false)
    private PostOffice destinationPostOffice;
}
