package com.poryvai.post.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDateTime;

/**
 * Represents a log entry for an employee's action on a parcel.
 * This entity records a specific event, such as a parcel being received or delivered,
 * and links it to the employee who performed the action and the parcel itself.
 */
@Entity
@Table(name = "parcel_log_entry")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
public class ParcelLogEntry {

    /**
     * Unique identifier for the log entry in the database.
     * This ID is auto-generated by the database upon entity persistence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * The timestamp when the action was performed.
     */
    @Column(name = "timestamp", nullable = false)
    private LocalDateTime timestamp;

    /**
     * The type of action performed by the employee (e.g., "RECEIVED", "DELIVERED").
     * Stored as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "action_type", nullable = false, length = 50)
    private ParcelLogEntryActionType actionType;

    /**
     * The {@link Employee} who performed the action.
     * Establishes a many-to-one relationship with the Employee entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;

    /**
     * The {@link Parcel} entity that the action was performed on.
     * Establishes a many-to-one relationship with the Parcel entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parcel_id", nullable = false)
    private Parcel parcel;

    /**
     * The {@link PostOffice} where the action took place.
     * This establishes a many-to-one relationship with the PostOffice entity.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_office_id", nullable = false)
    private PostOffice postOffice;
}
