package com.poryvai.post.model;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldNameConstants;

/**
 * Represents a Post Office entity in the system.
 * This class maps to a database table and holds details about a specific post office.
 */
@Entity
@Table(name = "post_office")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
public class PostOffice {

    /**
     * Unique identifier for the Post Office in the database.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * The name of the post office.
     */
    @Column(name = "name", unique = true, nullable = false, length = 255)
    private String name;

    /**
     * The city where the post office is located.
     */
    @Column(name = "city", nullable = false, length = 80)
    private String city;

    /**
     * The postal code of the post office.
     */
    @Column(name = "postcode", nullable = false, length = 10)
    private String postcode;

    /**
     * The street name and building number of the post office (e.g., "Khreshchatyk, 22").
     */
    @Column(name = "street", nullable = false, length = 255)
    private String street;
}
