package com.poryvai.post.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldNameConstants;

import java.util.List;

/**
 * Represents a Post Office entity in the system.
 * This class maps to a database table and holds details about a specific post office.
 */
@Entity
@Table(name = "post_office")
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
@ToString(exclude = "employees")
public class PostOffice {

    /**
     * Unique identifier for the Post Office in the database.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * The name of the post office.
     */
    @Column(name = "name", unique = true, nullable = false, length = 255)
    private String name;

    /**
     * The city where the post office is located.
     */
    @Column(name = "city", nullable = false, length = 80)
    private String city;

    /**
     * The postal code of the post office.
     */
    @Column(name = "postcode", nullable = false, length = 10)
    private String postcode;

    /**
     * The street name and building number of the post office (e.g., "Khreshchatyk, 22").
     */
    @Column(name = "street", nullable = false, length = 255)
    private String street;

    /**
     * A list of {@link Employee} entities who work at this post office.
     * This field establishes a one-to-many relationship, where the "postOffice" field
     * in the Employee entity is the owning side.
     */
    @OneToMany(mappedBy = "postOffice", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JsonManagedReference
    private List<Employee> employees;
}
